# -*- coding: utf-8 -*-
"""Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a6R0dJ-DmkOvVIXQf_aWbIJKsxtV_y7w
"""

idade_renata = 14
idade_fabiana = 18
dinheiro_iara = 6000.00

if (idade_renata >= 14 and idade_fabiana == 19 or dinheiro_iara == 5000.00 ):
  situação = 'vai viajar'
else:
  situação = 'não vai viajar'

print(f'Rodrigo {situação} para Portugal')

sabeSambar = 'sim'
gostaFeijoada = 'sim'
torceSelecaoBrasileira = 'não'

if (sabeSambar == 'sim' or gostaFeijoada == 'sim' and torceSelecaoBrasileira == 'sim'):
  print('Esse é brasileiro')
else:
  print('Esse não é brasileiro')

temDentes = 'sim'
temFome = 'não'
gosta = 'sim'

if temDentes == 'sim':
    TDcondicao = 'verdadeiro'
elif temDentes == 'não':
    TDcondicao = 'falso'

if temFome == 'sim':
    TFcondicao = 'verdadeiro'
elif temFome == 'não':
    TFcondicao = 'falso'

if gosta == 'sim':
    Gcondicao = 'verdadeiro'
elif gosta == 'não':
    Gcondicao = 'falso'

if Gcondicao == 'falso' or TFcondicao == 'falso':
    GTFcondicao = 'falso'
else:
    GTFcondicao = 'verdadeiro'

if GTFcondicao == 'verdadeiro' and TDcondicao == 'verdadeiro':
    Fcondicao = 'verdadeiro'
else:
    Fcondicao = 'falso'

print(f'A pessoa precisa ter dentes {TDcondicao} e ter fome {TFcondicao} ou gostar de maçã {Gcondicao} - Resposta final {Fcondicao}')